apiVersion: v1
kind: ReplicationController
metadata:
  name: helloserver-controller
spec:
  replicas: 2
  selector:
    app: helloserver
  template:
    metadata:
      labels:
        app: helloserver
    spec:
      containers:
        - name: helloserver-container
          image: eriksonmurrugarra/hello-server
          ports:
          - containerPort: 3000